//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//

var numm = 600851475143;
var largestFact = 0;
var factors = [2];

for (var i = 2; i * i < numm; i++) {
    if (numm % i == 0) { // It is a divisor
        factors[0] = i;
        factors[1] = numm / i;

        for (var k = 0; k < 2; k++) {
            var isPrime = true;
            for (var j = 2; j * j <  factors[k]; j++) {
                if (factors[k] % j == 0) {
                    isPrime = false;
                    break;
                }
            }
            if (isPrime && factors[k] > largestFact) {
                largestFact = factors[k];
            }
        }
    }
}
console.log(largestFact);
