/**
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * @type {number}
 */
var total = 0;

var v1=1;
var v2=1;

for (var i= 1; i<4000000; i++) {
    fib(v1, v2, function (vv1, vv2) {

        if(vv1%2 === 0) {
            total = total + vv1;

            v1 = vv1;
            v2 = vv2;
            console.log(v1,v2)
        };
    });

    };


function fib(v1,v2, callback){
    return callback(v1+v2, v1);
}

console.log(total);
